# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    suffle:
        class: AppBundle\Service\ShuffleService
    pop:
        class: AppBundle\Service\PopService
        arguments: ["@suffle","@repository_post","@repository_question"]

    repository_post:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.default_entity_manager", getRepository]
            arguments: ["AppBundle:Post"]
    repository_question:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.default_entity_manager", getRepository]
            arguments: ["AppBundle:Question"]